/*const data = {
    "productos": [{
        nombre: "Agenda 16 meses",
        precio: 20.99,
        categoria: "Agenda",
        desc: "Agenda de espiral de tapas ligeras de polipropileno reciclado, procedente de residuos y polución del mar. Ideal para avanzarse en la organización del año natural con 16 meses completos: inicio en septiembre de 2023 y finalización en diciembre de 2024. Con goma elástica y esquinas microperforadas para localizar rápidamente el día/semana en curso.Incluye adhesivos temáticos orientados a la organización personal. Agenda con información de interés en la anualidad y otros contenidos extra. Gran formato, ideal para negocios: restaurantes, peluquerías, etc. Duración: Septiembre 2023 - Diciembre 2024 (16 meses) Interior: 1 Día Página Con información en la anualidad de los festivos de los siguientes países: Argentina, Australia, Bélgica, Brasil, Suiza, Chile, Alemania, España, Francia, Reino Unido, Irlanda, Italia, Luxemburgo, Mónaco, México, Países Bajos, Polonia, Portugal, Rumanía, Rusia, Suecia, Ucrania y Estados Unidos. La anualidad de la agenda incluye la información relativa a festivos. La agenda dispone también de otros contenidos extra: datos personales, calendarios, fechas a destacar, códigos de países, mapa de los husos horarios, festivos internacionales, tallas de ropa, horario, cosas que hacer, plan mensual en columnas de 3 años, planificación mensual cuadriculada de 16 meses, hojas para anotaciones, hojas para contactos y set de adhesivos temáticos. Agenda multilingüe: inglés, francés, italiano, alemán, español, neerlandés, portugués y catalán. Formato: E40 - 210x297. Tapas de polipropileno reciclado procedente de residuos y polución del mar, espiral simple metálica y papel. 70gr/m2. Papel FSC® ecológico libre de cloro elemental y de ácido, fabricado mediante la utilización de energías limpias, con el 100% de celulosa controlada, y bajo los certificados de calidad ISO9001:2015 y medio ambiente ISO14001:2015, cumpliendo así la normativa ISO9706 sobre la permanencia del papel. El Forest Stewardship Council® (FSC®) es una organización no gubernamental, independiente, sin ánimo de lucro, establecida para promover una gestión forestal ambientalmente responsable, socialmente beneficiosa y económicamente viable en los bosques de todo el mundo.",
        imagen: "/img/https://vinifan.com/wp-content/uploads/2020/01/Objeto-inteligente-vectorial-copia-3-4.png",
    },
    {
        nombre: "Agenda",
        precio: 23.99,
        categoria: "Agenda",
        desc: "Agenda Pastel Quo Vadis - Interior: PLAN NOTE 15x21 cm Multilingüe. La gama Pastel de Quo Vadis, una gama de agendas y cuadernos con tacto aterciopelado subrayada por un discreto marcaje. El accesorio de moda para un año perfecto. Duración 16 meses: Septiembres a diciembre. La agenda 2 en 1: 1 página semanal y 1 página para notas. Contenidos extra: Horario (Lunes a Domingo), Listado de cumpleaños, Lista de deseos, Apartado de presupuestos para vacaciones, horarios, listados telefónicos Informaciones prácticas. Resumen temporal del mes en curso, zona gris para resaltar anotaciones importantes y pestañas para una navegación fácil y rápida para todos los meses. Papel en color blanco - Encuadernación cosida - Tamaño A5 (15x21cm) - Nº de páginas: 208. Idiomas: Multilingüe (Castellano, Inglés, Francés, Italiano, Alemán, Holandés).",
        imagen: "/img/https://vinifan.com/wp-content/uploads/2020/01/Objeto-inteligente-vectorial-copia-3-4.png",
    },
    {
        nombre: "Agenda escolar Universal",
        precio: 29.99,
        categoria: "Agenda",
        desc: "Agenda DÍA PÁGINA de septiembre a agosto, septiembre mes vista (con días Mundiales e Internacionales declarados por las Naciones Unidas, santoral y fases de la Luna), mapas, 27 páginas cuadriculadas a color, mapas.FORMATO: cubiertas encapsuladas en PVC, espiral de plástico y cierre con goma elástica. 288 páginas tamaño 12,5 x 17 cm, con uñero microperforado, papel ecológico.",
        imagen: "/img/https://vinifan.com/wp-content/uploads/2020/01/Objeto-inteligente-vectorial-copia-3-4.png",
    },
    {
        nombre: "Bolígrafo borrable Pilot",
        precio: 4.99,
        categoria: "Boligrafo",
        desc: "Paquete de 3 bolígrafos de tinta que se puede borrar Pilot Frixion Point, para escribir sobre papel. Tiene una punta de aguja de 0,25 mm que permite escribir con precisión.Para borrar la tinta, hay que frotar el texto con la goma que hay a la punta del bolígrafo.El bolígrafo es del mismo color que la tinta, y en la parte inferior tiene una empuñadura que reduce la fatiga en la hora de escribir y hace que se coja más cómodamente.La caja incluye 1 bolígrafo de color negro, 1 azul y 1 rojo.",
        imagen: "/img/boliBorrable.jpg",
    },
    {
        nombre: "Calendario 16 Meses",
        precio: 19.99,
        categoria: "Calendario",
        desc: "El calendario dispone también de otros contenidos extra: calendario anual del año y del año siguiente, planning anual, listado de festivos de las CC. AA. y de las capitales de provincia e inicios de los años nuevos chino, musulmán, ortodoxo y hebreo. Idioma del artículo: español. Formato: S - 210x150. Papel y doble espiral metálica. 120gr/m2. Papel FSC® ecológico libre de cloro elemental fabricado bajo los certificados de calidad ISO9001:2015 y medio ambiente ISO14001:2015, cumpliendo así la normativa ISO9706 sobre la permanencia del papel. El Forest Stewardship Council® (FSC®) es una organización no gubernamental, independiente, sin ánimo de lucro, establecida para promover una gestión forestal ambientalmente responsable, socialmente beneficiosa y económicamente viable en los bosques de todo el mundo.",
        imagen: "/img/calendario.jpg",
    },
    {
        nombre: "Cartolina Artés",
        precio: 2.50,
        categoria: "Cartolina",
        desc: "Cartulina Artés de 180g. Colro amarillo gualda. Paquete de 25 unidades",
        imagen: "/img/cartolinacolores.jpg",
    },
    {
        nombre: "Bloc Dibujo Oxford A4",
        precio: 9.50,
        categoria: "Dibujo",
        desc: "El BLOC ESPIRAL DE DIBUJO ESCOLAR de Oxford, en formato A4+, está fabricado con papel artístico color natural de alta calidad de 130gr, con una superfície rugosa lo que lo hace muy versátil permitiendo utilizar en él varias técnicas como lápiz, pastel, rotuladores o tinta. Su papel también permite líneas gruesas y finas y efectos de sombras. Su tapa frontal es una tapa blanda, mientras que la contratapa es rígida, lo que permite tener además un refuerzo como soporte. Sus 20 hojas son lisas y microperforadas para poder arrancarlas fácilmente. Además, éste bloc espiral cuenta con la certificación FSC y está fabricado en Europa.",
        imagen: "/img/dibujo.jpg",
    },
    {
        nombre: "Estuche iTotal Unicornio",
        precio: 5.99,
        categoria: "Estuches",
        desc: "Estuche iTotal Unicornio. Estuche rectangular con cremallera, con estampado de Unicornio. Medidas: 230 x 60 mm.",
        imagen: "/img/Estuche.jpg",
    },
    {
        nombre: "Libreta A5 espiral",
        precio: 13.99,
        categoria: "Libretas",
        desc: "Libreta espiral Escolofi tamaño A5, 50 hojas, 70 g/m², liso. Tapa dura.",
        imagen: "/img/libretaA5.jpg",
    },
    {
        nombre: "Recambio libreta ",
        precio: 18.50,
        categoria: "Libretas",
        desc: "Recambio para libretas Miquelrius. El bloc está encolado por el lomo e incluye 100 hojas de tamaño A4 microperforadas, y con 4 agujeros para encuadernadores de anillas.Papel extra opaco, con cuadrícula de 5 mm y gramaje de 70 g/m².Bordes de color verde, gris, rosa y azul para diferenciar los contenidos.Cuenta con el sello FSC que garantiza que el material utilizado es procedente de bosques controlados.",
        imagen: "/img/libretaBlanca.jpg",
    },
    {
        nombre: "Note Book 10 A4",
        precio: 17.60,
        categoria: "Libretas",
        desc: "El EUROPEANBOOK 10 de OXFORD CLASSIC es el cuaderno ideal para aquellos que buscan un cuaderno espiral con hojas microperforadas y varios colores de recuadro que te ayuda a organizarte por color según la asignatura o tema, o para romper la monotonía. ¡Nada menos que 10 colores de recuadro! Tiene tapas extraduras con Write&Erase, pizarra blanca en el interior de las tapas para cálculos, anotaciones, borradores,... ¡Y evitar así malgastar papel! Gracias a sus 4 taladros podrás archivar fácilmente las hojas en tu Europeanbinder, Carpeta de anillas o archivador. Además, todos los europeanbooks Oxford son compatibles con al APP gratuita Scribzee, que te permite tener todas tus notas manuscritas digitalizadas en el móvil con us simple gesto, para consultar, organizar y compartir!",
        imagen: "/img/libretas.jpg",
    },
    {
        nombre: "Mochila lila",
        precio: 35.99,
        categoria: "Botas",
        desc: "Mochila lisa ideal para el curso escolar. De tela resistente. Compartimento principal para libros y PC + bolsillo frontal para guardar el material más pequeño. Cierre con cremallera resistente y tiradores metálicos. Elige el color que más te guste!",
        imagen: "/img/mochila.jpg",
    },
    {
        nombre: "Papel 10 Colores A4",
        precio: 16.99,
        categoria: "Papeleria",
        desc: "Papel de 10 colores tamaño DIN A4 de la marca para uso diario. Recomendado para la escritura y para cualquier clase de impresora y fotocopiadora. Grosor de 80 gramos. Incluye 100 hojas. El tamaño de los folios es de 210 mm por 297 mm.Escoger la marca  es apostar por productos de proximidad, sostenibles y de gran calidad.",
        imagen: "/img/papel10colores.jpg",
    },
    {
        nombre: "Rotuladores Maped Nightfall ",
        precio: 16.99,
        categoria: "Rotuladores",
        desc: "Este estuche Nightfall de Maped contiene 24 rotuladores de colores brillantes e intensos ideales para pintar y escribir.La punta mide 2,5 mm de diámetro, es suave y resistente y se desliza cómodamente sobre el papel. La tinta puede limpiarse fácilmente de las manos y la ropa.El aspecto exterior de los rotuladores es de colores metálicos y el cuerpo es triangular y ergonómico.La colección Nightfall de Maped combina ergonomía, calidad y diseño y es ideal para su uso escolar.",
        imagen: "/img/rotuladores.jpg",
    },
    {
        nombre: "Marcador fluor. Boss pastel 6 colores",
        precio: 6.90,
        categoria: "Subrayador",
        desc: "Estuche de 6 marcadores Stabilo Boss de colores pastel. Es un rotulador fluorescente, pero con colores suaves que aportan un look sutil y estiloso.Tienen la punta biselada y un trazo de 2 mm y 5 mm.Sirven para resaltar, marcar y subrayar las partes destacadas de apuntes y documentos.Tinta con base acuosa y resistente a la luz. Apta para todo tipo de papel y con tecnología antisecado que ofrece hasta 4 horas de protección.",
        imagen: "/img/subrayador.jpg",
    },
    {
        nombre: "Mini grapadora Maped",
        precio: 16.40,
        categoria: "Grapadora",
        desc: "La mini grapadora Nightfall de Maped es de pequeño formato, fácil de transportar y almacenar.Incluye 400 grapas y tiene quitagrapas incorporado.La profundidad de grapado es de 29 mm. Puede grapar hasta 12 hojas con grapas 24/6 y hasta 15 hojas con grapas 26/6. Tiene capacidad para 41 grapas 24/6 o 58 grapas 26/6.La colección Nightfall de Maped combina ergonomía, calidad y diseño y es ideal para uso escolar.",
        imagen: "/img/grapadora.jpg",
    },
    ],
};

export async function getProductes() {

    return data.productos;
}*/